# Generated by Django 5.2.4 on 2025-08-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="application_link",
            field=models.URLField(
                blank=True, help_text="Link where students will be redirected to apply"
            ),
        ),
    ]
